name: SkyblockDragons
version: '${project.version}'
main: me.maxiiiiii.skyblockdragons.SkyblockDragons
description: Skyblock Dragons but in java
softdepend: [HolographicDisplays]
commands:
  Anvil:
    permission: skyblockdragons.anvil
    usage: /<command>
    aliases:
      - ja
      - anvil
      - av
  SkyblockDragons:
    permission: skyblockdragons.plugin
    usage: /<command> <text>
    aliases:
      - jp
      - sd
  Menu:
    permission: skyblockdragons.menu
    usage: /<command> <player>
    aliases:
      - jm
      - menu
      - sbmenu
  Item:
    permission: skyblockdragons.item
    usage: /<command> <item> <amount>
    aliases:
      - ji
      - jItem
      - javaI
      - item
  Stat:
    permission: skyblockdragons.stat
    usage: /<command> <number>
  EnchantingTable:
    permission: skyblockdragons.enchanting
    usage: /<command>
    aliases:
      - et
      - enchantingt
      - etable
  ReforgeMenu:
    permission: skyblockdragons.reforge
    usage: /<command>
    aliases:
      - ref
      - rm
      - reforgem
      - rmenu
  Book:
    permission: skyblockdragons.book
    usage: /<command> <enchant> <level>
    aliases:
      - jb
      - javab
      - jbook
  AccessoryBag:
    permission: skyblockdragons.accessorybag
    usage: /<command> <player>
    aliases:
      - ac
      - acb
      - acbag
  ViewRecipe:
    permission: skyblockdragons.viewrecipe
    usage: /<command> <recipe>
  CraftingTable:
    permission: skyblockdragons.craftingtable
    usage: /<command>
  Bits:
    permission: skyblockdragons.bits
    usage: /<command> <text> <object> [<object>]
  PlayTime:
    permission: skyblockdragons.playtime
    usage: /<command>
  SkillMenu:
    permission: skyblockdragons.skill.menu
    usage: /<command>
  SkillAdmin:
    permission: skyblockdragons.skill.admin
    usage: /<command> <skill-name> <text> [<amount>] [<player>]
  Wardrobe:
    permission: skyblockdragons.wardrobe.open
    usage: /<command> <page> <player>
    aliases:
      - wd
  PetAdmin:
    permission: skyblockdragons.pet.admi
    usage: /<command> <pet>
    aliases:
      - pa
      - peta
  PetMenu:
    permission: skyblockdragons.pet.menu
    usage: /<command> <page>
    aliases:
      - pm
      - pets
  FlyTo:
    permission: skyblockdragons.flyto
    usage: /<command> <ticks>
  Bank:
    permission: skyblockdragons.bank
    usage: /<command> <text>
  Sound:
    permission: skyblockdragons.sound
    usage: /<command> <sound> <pitch>
  EntitySD:
    permission: skyblockdragons.mob.spawn
    usage: /<command> <mob>
    aliases:
      - esd
  Coop:
    permission: skyblockdragons.coop
    usage: /<command> <text> <player>
  Variables:
    permission: skyblockdragons.variables
    usage: /<command> <text>
    aliases:
      - var
  Sell:
    permission: skyblockdragons.sell
    usage: /<command>
  Recipes:
    permission: skyblockdragons.recipes
    usage: /<command>
  RecipesFor:
    permission: skyblockdragons.recipesfor
    usage: /<command>
  RecipesWith:
    permission: skyblockdragons.recipeswith
    usage: /<command>
  Warp:
    permission: skyblockdragons.warp
    usage: /<command> <warp>
  Hub:
    permission: skyblockdragons.hub
    usage: /<command>
  Test:
    permission: skyblockdragons.test
  Profile:
    permission: skyblockdragons.profile
    usage: /<commamd> [<player>]
  Storage:
    permission: skyblockdragons.storage
    usage: /<command>
  EnderChest:
    permission: skyblockdragons.enderchest
    usage: /<command> [<page>]
    aliases:
      - ec
  Forge:
    permission: skyblockdragons.forge
    usage: /<command>
  ForgeMilestone:
    permission: skyblockdragons.forge.milestone
    usage: /<command> <text> [<amount>]
  SkyblockDragonsTest:
    aliases:
      - sdtest
      - testsd
    permission: skyblockdragons.test
  Party:
    permission: skyblockdragons.party.command
    usage: /<command> <text> [<arg>]
    aliases:
      - p
  Chat:
    permission: skyblockdragons.chat.command
    usage: /<command> <channel>
  PartyChat:
    permission: skyblockdragons.party.chat
    usage: /<command> <message>
    aliases:
      - pc
      - pchat
      - partyc
      - ChatParty
      - cparty
      - chatp
  PartyList:
    permission: skyblockdragons.party.list
    usage: /<command>
    aliases:
      - pl
      - plist
      - playerl
      - listplayer
  Alpha:
    permission: skyblockdragons.alpha.command
    usage: /<command>
    aliases:
      - sdalpha
      - alpha
      - sbdalpha
      - alphasd
  CrystalGrinder:
    permission: skyblockdragons.crystal.menu
    usage: /<command>
    aliases:
      - cg
      - crystalmenu
  kill:
    permission: skyblockdragons.kill
    usage: /<command> <player>
  StatsAdmin:
    permission: skyblockdragons.basestats
    usage: /<command>
    aliases:
      - sa
  PowerStone:
    permission: skyblockdragons.powerstone.menu
    usage: /<command>
    aliases:
      - ps
  PowerStoneAdmin:
    permission: skyblockdragons.powerstone.admin
    usage: /<command> <text> [<player>]
    aliases:
      - psa
  ToggleUpdateItems:
    permission: skyblockdragons.admin
    usage: /<command>