package me.maxiiiiii.skyblockdragons.item.objects;

import lombok.Getter;

@Getter
public enum ItemFamily {
    ASPECT_OF_THE_END,
    BONZO_STAFF,
    LEAPING_SWORD,
    VOIDWALKER_KATANA,
    SOUL_WHIP,
    FLOWER_OF_TRUTH,
    SHADOW_FURY,
    SPIRIT_SCEPTRE,
    NECRON_BLADE,
    ELECTRO_MAGNET,
    ROGUE_SWORD,
    JUJU,
    BONEMERANG,
    NECRON_ARMOR,
    STORM_ARMOR,
    SUPERIOR_DRAGON_ARMOR,
    JUNGLE_AXE,
    REFORGE_STONE,
    SKIN,
    NETHER_ARTIFACT,
    SCROLL,
    TORNADO_WAND,
    PARABOLA_WAND,
    TROLL,
    GRAPPLING_HOOK,
    GYROKINETIC_WAND,
    ITEM,
    ENCHANTED_ITEM,
    BOOK,
    RADIANT_POWER_ORB,
    BUILDERS_WAND,
    REVENANT_FALCHION,
    MIDAS_STAFF,
    ICE_SPRAY_WAND,
    HOT_POTATO,
    ERRORMERANG_WAND,
    BACKPACK,
    VANILLA,
    SLIME,
    PIGMAN,
    WOOD,
    LEATHER,
    STONE,
    CHAIN,
    IRON,
    GOLD,
    LAPIS,
    REDSTONE,
    EMERALD,
    DIAMOND,
    OBSIDIAN,
    NULL
}


/*
    ASPECT_OF_THE_END(new ArrayList<>(Arrays.asList(ItemMaterial.ASPECT_OF_THE_END, ItemMaterial.ASPECT_OF_THE_VOID))),
    BONZO_STAFF(new ArrayList<>(Arrays.asList(ItemMaterial.BONZO_STAFF))),
    LEAPING_SWORD(new ArrayList<>(Arrays.asList(ItemMaterial.LEAPING_SWORD))),
    VOIDWALKER_KATANA(new ArrayList<>(Arrays.asList(ItemMaterial.ATOMSPLIT_KATANA))),
    SOUL_WHIP(new ArrayList<>(Arrays.asList(ItemMaterial.SOUL_WHIP))),
    FLOWER_OF_TRUTH(new ArrayList<>(Arrays.asList(ItemMaterial.FLOWER_OF_TRUTH))),
    SHADOW_FURY(new ArrayList<>(Arrays.asList(ItemMaterial.SHADOW_FURY))),
    SPIRIT_SCEPTRE(new ArrayList<>(Arrays.asList(ItemMaterial.SPIRIT_SCEPTRE))),
    NECRON_BLADE(new ArrayList<>(Arrays.asList(ItemMaterial.VALKYRIE))),
    ELECTRO_MAGNET(new ArrayList<>(Arrays.asList(ItemMaterial.ELECTRO_MAGNET))),
    JUJU(new ArrayList<>(Arrays.asList(ItemMaterial.TERMINATOR))),
    BONEMERANG(new ArrayList<>(Arrays.asList(ItemMaterial.BONEMERANG))),
    NECRON_ARMOR(new ArrayList<>(Arrays.asList(ItemMaterial.NECRON_HELMET, ItemMaterial.NECRON_CHESTPLATE, ItemMaterial.NECRON_LEGGINGS, ItemMaterial.NECRON_BOOTS))),
    STORM_ARMOR(new ArrayList<>(Arrays.asList(ItemMaterial.STORM_HELMET, ItemMaterial.STORM_CHESTPLATE, ItemMaterial.STORM_LEGGINGS, ItemMaterial.STORM_BOOTS))),
    SUPERIOR_DRAGON_ARMOR(new ArrayList<>(Arrays.asList(ItemMaterial.SUPERIOR_DRAGON_HELMET, ItemMaterial.SUPERIOR_DRAGON_CHESTPLATE, ItemMaterial.SUPERIOR_DRAGON_LEGGINGS, ItemMaterial.SUPERIOR_DRAGON_BOOTS))),
    JUNGLE_AXE(new ArrayList<>(Arrays.asList(ItemMaterial.TREE_CAPITATOR))),
    REFORGE_STONE(new ArrayList<>(Arrays.asList(ItemMaterial.PRECURSOR_GEAR, ItemMaterial.WITHER_BLOOD, ItemMaterial.NECROMANCER_BROOCH))),
    SKIN(new ArrayList<>(Arrays.asList(ItemMaterial.SUPERIOR_DRAGON_HELMET_SKIN, ItemMaterial.STORM_HELMET_SKIN, ItemMaterial.SUPERIOR_DRAGON_HELMET_SKIN))),
    NETHER_ARTIFACT(new ArrayList<>(Arrays.asList(ItemMaterial.NETHER_ARTIFACT))),
    TORNADO_WAND(new ArrayList<>(Arrays.asList(ItemMaterial.TORNADO_WAND, ItemMaterial.HURRICANE_WAND, ItemMaterial.TWISTER_WAND))),
    PARABOLA_WAND(new ArrayList<>(Arrays.asList(ItemMaterial.PARABOLA_WAND))),
    TROLL(new ArrayList<>(Arrays.asList(ItemMaterial.TROLL_EYE))),
    GRAPPLING_HOOK(new ArrayList<>(Arrays.asList(ItemMaterial.GRAPPLING_HOOK))),
    GYROKINETIC_WAND(new ArrayList<>(Arrays.asList(ItemMaterial.GYROKINETIC_WAND))),
    ITEM(getNormalItems()),
    ENCHANTED_ITEM(getEnchantedItems()),
    BOOK(new ArrayList<>(Arrays.asList(ItemMaterial.ENCHANTED_BOOK))),
    NULL(new ArrayList<>());
 */